### ISSUE TITLE
Realizar Diagrama de Espina de Pescado

### ISSUE THREAD

**Issue by Katherine-Zapata** [Katherine-Zapata/equipo1_sac_ppi2020#2]

**Comment by marthaduque** [comment]
El diagrama de espina de pescado se debe hacer es del proyecto Jugando y aprendiendo

**Comment by marthaduque** [comment]
Corregir el diagrama teniendo en cuenta que va el probema en  la cabeza del pescado y las causas de dicho problema en el cuerpo del pescado
