### ISSUE TITLE
Hacer tablero de Visión del producto

### ISSUE THREAD

**Issue by Katherine-Zapata** [Katherine-Zapata/equipo1_sac_ppi2020#5]

**Comment by marthaduque** [comment]
debe comenzar el nombre de la actividad con un verbo en infinitivo

**Comment by marthaduque** [comment]
Mejorar la redacción de la visión, necesidades y características.

**Comment by marthaduque** [comment]
Corregir la redacción de la visión de acuerdo al documento de la segunda semana de IR.
